apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: argocd